### ISSUE TITLE
Crash when using version 1.2.4 with Minecraft 1.21.1

### ISSUE THREAD

**Issue by notrohit1702** [MDLC01/better-game-mode-switcher-mc#3]
latest.log: https://mclo.gs/dj3qtFW

[Version 1.2.4](https://modrinth.com/mod/better-game-mode-switcher/version/1.2.4) despite being marked as compatible with Minecraft 1.21.1, causes a crash with it. This version shows on the top of the list for 1.21.1 versions. Therefore, I request that, in order to avoid confusion, it shouldn't be marked as such.

**Comment by MDLC01** [comment]
Thanks for reporting the issue. Could you tell me if 1.2.3 works with Minecraft 1.21.1 on your computer? There should be no difference between 1.2.3 and 1.2.4 appart from the list of supported versions.

**Comment by MDLC01** [comment]
On my machine, I am able to launch Minecraft 1.21.1 with Better Game Mode Switcher 1.2.4. This will need more investigation to understand what exactly causes the issue on your machine.

**Comment by notrohit1702** [comment]
> Thanks for reporting the issue. Could you tell me if 1.2.3 works with Minecraft 1.21.1 on your computer? There should be no difference between 1.2.3 and 1.2.4 appart from the list of supported versions.

Yes, 1.2.3 works completely fine.

**Comment by notrohit1702** [comment]
> On my machine, I am able to launch Minecraft 1.21.1 with Better Game Mode Switcher 1.2.4. This will need more investigation to understand what exactly causes the issue on your machine.

Hmm, that's weird..

**Comment by MDLC01** [comment]
I released a new version: 1.2.5, which adds support for Minecraft 1.21.4. It should be compatible with all previous version of Minecraft, starting at Minecraft 1.20.5. Can you tell me if it works on your machine with Minecraft 1.21.1?

**Comment by baseb01** [comment]
> I released a new version: 1.2.5, which adds support for Minecraft 1.21.4. It should be compatible with all previous version of Minecraft, starting at Minecraft 1.20.5. Can you tell me if it works on your machine with Minecraft 1.21.1?

Crashes on my machine on Minecraft 1.2.1.1 if I use either 1.2.4 or 1.2.5, only 1.2.3 works

**Comment by MDLC01** [comment]
Could you send a crash report when using Better Game Mode Switcher 1.2.5 with Minecraft 1.21.1?

**Comment by baseb01** [comment]
> Could you send a crash report when using Better Game Mode Switcher 1.2.5 with Minecraft 1.21.1?

[crash-2024-12-15_22.25.49-client.txt](https://github.com/user-attachments/files/18142390/crash-2024-12-15_22.25.49-client.txt)

**Comment by MDLC01** [comment]
Better Game Mode Switcher versions 1.2.4 and 1.2.5 are no longer marked as supporting Minecraft versions 1.20.5, 1.20.6, 1.21, and 1.21.1 on Modrinth and GitHub.
